#ENC[AES256_GCM,data:pp8I4EMViZJoup1XAUA9vP8/0SgannnI4p4m+Foxy6jZW8E/l5GzoHoQ7ozM821rgngabh74KTiqtbkE8VkKsONwIYfZoB483tKl/Q==,iv:aAYA2oNXUzvhH4ystL0jvxoanJO40ygZE+1DrGTkbr4=,tag:zj/BtfQXmJ7Nbqj2bbUO3g==,type:comment]
#ENC[AES256_GCM,data:3mDASCY/K6wjbUIppkN5dtJ+qudUpAcHyBYv552IxzHR1DIeYg==,iv:mMmRqrA0vGsHO0S3LDtzBJ6UNWoY+RgeagpN7ogr8rc=,tag:TJBlTUjaQRPk/nicy0EqyQ==,type:comment]
#
#ENC[AES256_GCM,data:GOtU0YSn544r/A1v4/mIFSeh5MNDTOJYcEev6BovOg0wK87+OcM7HW7j/oDKpd5otSkbWohzpfOcAvYDjEOnKI0gQe36GIHa5+Ule+Bb5qSdAK4I5FH+FfRT5QIfBqvx0g==,iv:nB59qGIIvoQFRAYUts8wF+NiK7VKjApI/t72OEndMjE=,tag:92nBIXU2d2oAX2to3xASnA==,type:comment]
#ENC[AES256_GCM,data:UNQwp/APp+hOW8bn7PRQjdtGKC1DgzcgHJQ3JhaKfsPxC5W8pCJmJ0IVokgUS4nN4TqAcoi/tN4In7IvQokYBl695wI6/C+mmSDZpJzZ5MLjf9jmj3Qn2Eyi5kvi2dA8o29LcqhNHVQUQ2ClSFNsLs0NtZ6VHraA50VW5xTeIGw0OQ==,iv:wk0Ym3BMWx0Fh2GE3ChFcMXho3sz4pF1Q2We0DTeUxM=,tag:+Zjv3RgOKf1Rt5sB7rkCHg==,type:comment]
#ENC[AES256_GCM,data:cWc6GjX30Rb+NZ8XeUBkJuZ1R5dA9r8k9VJgaTi+aA==,iv:ipn4rwcBFpa9fJKQxPERIx2TLwERdtWavYOBvTsKJt4=,tag:8honMtNkTPBDj2KGfYbKLw==,type:comment]
secrets:
    DB_USER: ENC[AES256_GCM,data:9YvF4FHqdic=,iv:WMafeDI63P7S9v98XE/hMrjYKlecjG/sDb0ic+eIVt4=,tag:8VzRYE2bQcOWYVbccmm0fw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3d9pFARFyUw=,iv:YQUzXElhm8pMaO5Pna62S4rMFHt8wJwSUdA0jYR5MPw=,tag:ExaK0wc1U8pWo19JOnt69g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYXBTWnBKSUNkTDI0SWxx
            K2pielJDSk5rWjZkRWV2TFJOcFU3NDBjZXg0CkdkMUFRWmZrK2d4N2lTSERPVEFG
            R3UwWUY1TS9RNTY0bWQ2RUpReGRORHMKLS0tIFhZSWs1STNic1VSYmQ1REtHMnhU
            WmMyRVdvNGc1OWd6cTZ6MWE1eEtnMHcK1m9lhxsJmtKY9HKNySXemCClrrir+yWd
            KkTmrGauiQ5HcACjg5vkyUefYNoUQBt64IXPmRKfos2ja+aBHJOFbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grru8e89e57ukuvud3x5nxk9kjra8vcw89krz4sl47uza3g9e9gqrjn2zs
    lastmodified: "2026-08-20T14:12:53Z"
    mac: ENC[AES256_GCM,data:8TsUvWrRQxwXBhNjId20N2AwmtpCpBQWItKXav24df4x1wFj3EzzEhXfhFrn7e2hbMX/7V6lyA8iCOfnjw6j2B8uBQHxssn3T33VDTg/iDfTuaa73TVAG371GPwdfG6CAqsyKfzEcCab1LvdRhd8U777c6j/yUmsOhH3oxyNTYI=,iv:XgW2TRo2gqfd+muqHkc40E1eWQA1MHczHneGwAz51GA=,tag:QinZesBRyzdCOpHhk06MJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
