#ENC[AES256_GCM,data:AZCV1P6h+9bcBngXr6lKdcEABCt4ZggEF54QGPTcqLeYP5IUE8jq483i/rwT3U0XPVNDIPF/eCcfNEUShweX/tg4OMXPQPKpuCSL25vEfy1FAQK7QUcKfBWSqhiEnh0P64csMok1JWeWuDpbCTsgp0cG/SkNIyid,iv:yOGF7RanKE6JYwdIsWOelkVKVc9q3m0ZI8DDsSAxAOE=,tag:JetZzyKRLUZihLmAoVvHlA==,type:comment]
#
#ENC[AES256_GCM,data:urm+DnZ5QsrZWLZ7hPL2IRLrXQACP3X22r9xVlyYIqMZ2j5xz94K5VPPCA6o45HOsGugkFRah33ruY0=,iv:YTlFOFOnIViEwZDpRKVR8ca3iBGHkaKjuyqxhK5ck4I=,tag:nJUeOGi83DP00GJTKFhdUA==,type:comment]
#ENC[AES256_GCM,data:/ujwewcrgZlV9cJTC6NLCJBUKCXMq7sQz68EAE90s5NjECuzRQF7WA==,iv:w26H16vLwHER2FJV2s48MdPNhrzvTh5H7uiGMADXPz0=,tag:w7Y3Tce2yQ1rhHoc1UrHAw==,type:comment]
#
#ENC[AES256_GCM,data:tuSyaBMLOEoxoQx9tpIGELj9nTiynt2k//NZe9fBcfkeM20WMWGWNhJHmvsVPUJP6kXoqfBjNtwQmJRO+RZsc3ZlZHXt/C4ix+nSZo+NH4OEmqmsRM7RCiKXWJmtG56StxgHvc7kWxc6KLyzvzy50TFFmVfB,iv:FN6k/ufb9xMggvh8WTIhSyCLvr6wIAMOzNukf838X5I=,tag:z6xyW7R94a5HCqpvrvqsJA==,type:comment]
#ENC[AES256_GCM,data:kiiE7r/pNLG6Kyg1X6oS5BBlH/CEYiQqobtjNQ3TpRaZE3wa6S17Yl4dYFc5DvXrLJm61nDMGUGnfqZEplZewZsMdMc8pCUzuGJOGMxt8dza5Z+RoLyUj5h2yWu8TJM+NCrtKYMVrIeJa1tqmnKddYT4hRVbpHdkwuNvDaHGAAHI/84JXTNk4oC+giRhbb1xaLQR03g=,iv:TcIfL/w1w6z2DCwrqGjTA835JDWFS4WYv+hhjJ6Wclk=,tag:xotBZbEZqGLV4HrtRwyRjQ==,type:comment]
secret:
    dbUser: ENC[AES256_GCM,data:YY9gYXPFkPU=,iv:VJZUb9dRLZz99mjA+Z1nuq662+WZbBziNJ/eqLHWH1U=,tag:Yu4EyfTyJ7PCuTmqWyDnGQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:XzoyV7JxckM=,iv:yro+grn3d07xWh54uadJAEw8Den9ZK0zq5Mcrdw3ywg=,tag:xpb+vD+5/dPL/CGWewO0Qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UU1JSmQ0WDErN2RtTjNk
            c2NKZmp1R3ZFMFdTTDlkanhYbE9xbkhaNlhrCjF5WEtKNE5uNVFKVGVXWnlmNCtK
            UjN6SjRzcWpkRTZjdndybVFyYTdUM2cKLS0tIERrYWdQSkloVUpJMDZjOWR3SXlX
            MHlBWndZTDJRbEtLQ3VLV0JwRjQ0bzQKudGlL23fzRSdPIhHA5pyyls6QGVt74ZH
            KckSFMABDe+SNmyXszAMz7BQ4tcwELaNram9xghsDRwh4z2XqcOZXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grru8e89e57ukuvud3x5nxk9kjra8vcw89krz4sl47uza3g9e9gqrjn2zs
    lastmodified: "2026-08-20T14:12:46Z"
    mac: ENC[AES256_GCM,data:Zw6gZwKQyNEVdYX/ez3KHfJ8HobOHy3Lgub+jFckVvNzT4KqogRQ9Oc660Z6bCqd5KAMH/v5W73A6CUV5VxREsnHy/ETVWyjR6meNWztWHDXZ0ugubt7J7Ig16jdn3TZ/uOFKNGz4YUied/t+CAniRT1TaWvqILeRjHfa/clT/w=,iv:Vlsm9pm3xdFOFw3VUtnIfkiJRFOJkjULfG+LhBHC+lU=,tag:SJH4ChX2FkFNi0JrBZ6SkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
